### ISSUE TITLE
Task execution failure

### ISSUE THREAD

**Issue by anilreddy789** [sonatype-nexus-community/nancy#268]
we are using sonatype-nexus OSS as a repository manager and having issues with the Task execution failure for the maven indexes 

what: Maven task index failure due to one of the repositories is failing to connect repository: proxy-maven-jboss-releases, when the task is set to run then the repo becomes remote unavailable service unavailable 
After running the task we are getting the following error
Task Name: Maven - publish indexes
Stack-trace:
org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to run task 'Publish Maven indexes of *'; 1 failure
	at org.sonatype.goodies.common.MultipleFailures.maybePropagate(MultipleFailures.java:95)
	at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:90)
	at org.sonatype.nexus.scheduling.TaskSupport.call(TaskSupport.java:100)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:143)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
	at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: org.sonatype.nexus.repository.proxy.ProxyServiceException: HTTP/1.1 503 Service Unavailable
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.mayThrowProxyServiceException(ProxyFacetSupport.java:509)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.fetch(ProxyFacetSupport.java:483)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.fetch(ProxyFacetSupport.java:417)
		at org.sonatype.nexus.repository.maven.internal.orient.MavenProxyFacet.fetch(MavenProxyFacet.java:117)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.doGet(ProxyFacetSupport.java:284)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.lambda$1(ProxyFacetSupport.java:260)
		at org.sonatype.nexus.common.io.CooperatingFuture.performCall(CooperatingFuture.java:122)
		at org.sonatype.nexus.common.io.CooperatingFuture.call(CooperatingFuture.java:64)
		at org.sonatype.nexus.common.io.ScopedCooperationFactorySupport$ScopedCooperation.cooperate(ScopedCooperationFactorySupport.java:99)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.get(ProxyFacetSupport.java:251)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.get(ProxyFacetSupport.java:240)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.prefetch(MavenIndexPublisher.java:245)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.prefetchIndexFiles(MavenIndexPublisher.java:227)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.publishProxyIndex(MavenIndexPublisher.java:160)
		at org.sonatype.nexus.repository.maven.internal.orient.OrientMavenProxyIndexFacet.publishIndex(OrientMavenProxyIndexFacet.java:96)
		at org.sonatype.nexus.repository.maven.tasks.PublishMavenIndexTask.execute(PublishMavenIndexTask.java:37)
		at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:79)
		... 13 more

Task Name: Maven - publish indexes
Stack-trace:
org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to run task 'Publish Maven indexes of *'; 1 failure
	at org.sonatype.goodies.common.MultipleFailures.maybePropagate(MultipleFailures.java:95)
	at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:90)
	at org.sonatype.nexus.scheduling.TaskSupport.call(TaskSupport.java:100)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:143)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
	at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: org.sonatype.nexus.repository.proxy.ProxyServiceException: HTTP/1.1 503 Service Unavailable
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.mayThrowProxyServiceException(ProxyFacetSupport.java:509)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.fetch(ProxyFacetSupport.java:483)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.fetch(ProxyFacetSupport.java:417)
		at org.sonatype.nexus.repository.maven.internal.orient.MavenProxyFacet.fetch(MavenProxyFacet.java:117)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.doGet(ProxyFacetSupport.java:284)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.lambda$1(ProxyFacetSupport.java:260)
		at org.sonatype.nexus.common.io.CooperatingFuture.performCall(CooperatingFuture.java:122)
		at org.sonatype.nexus.common.io.CooperatingFuture.call(CooperatingFuture.java:64)
		at org.sonatype.nexus.common.io.ScopedCooperationFactorySupport$ScopedCooperation.cooperate(ScopedCooperationFactorySupport.java:99)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.get(ProxyFacetSupport.java:251)
		at org.sonatype.nexus.repository.proxy.ProxyFacetSupport.get(ProxyFacetSupport.java:240)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.prefetch(MavenIndexPublisher.java:245)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.prefetchIndexFiles(MavenIndexPublisher.java:227)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.publishProxyIndex(MavenIndexPublisher.java:160)
		at org.sonatype.nexus.repository.maven.internal.orient.OrientMavenProxyIndexFacet.publishIndex(OrientMavenProxyIndexFacet.java:96)
		at org.sonatype.nexus.repository.maven.tasks.PublishMavenIndexTask.execute(PublishMavenIndexTask.java:37)
		at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:79)
		... 13 more

want to know why the repository proxy-maven-jboss-releases is failing to come online.
repo details:
maven 2
version-Release 
layout policy: strict 

Thanks,
Anil

**Comment by bhamail** [comment]
@anilreddy789 This issue does not appear to be related to Nancy. Sorry if I'm missing the point, but I think you'd be better off reaching out to forums dedicated to Nexus Repository Manager for help with this issue.

**Comment by madpah** [comment]
This issue appears to be about Sonatype Nexus Repository OSS, not Nancy. Please open a new issue in the appropriate repository. Closing as misfiled.
